# -*- coding: utf-8 -*-
"""Variable1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rzaErffru4PXMbF_PL70FAMP3YfTT6k5
"""

a1=45
a2=35

a1+a2

a1%a2

a1//a2

a1/a2

a,b,c,d=10,10.0,"sachin",True

c

a

# Commented out IPython magic to ensure Python compatibility.
# %a=10

b1=True
b2=False

b1-b2

b1+b2

b2-(-b1)

_int=1

a=10

str(a)

d='10'

int(d)

c=2+6j

type(c)

c.real

c.imag

c

b=int(input())

type(b)

b

s=input()

s

type(s)

s="sachin"

s[0]

s[4]

s[100]

s[-100]

s[0:7:1]

s[0:7]

s[:]

s[:7]

s[0:7:3]

s[::-1]

s1="pwskills"

s1[7:3:-1]

s1[7::-1]

s1[-1:-5:-1]

s1[-1::-1]

s1[0]='k'

